/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AdlCalendar {
    'colorInput': string;
    'endyear': number;
    'first': string;
    'last': string;
    'middle': string;
    'startyear': number;
    'titleCard': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLAdlCalendarElement extends Components.AdlCalendar, HTMLStencilElement {}
  var HTMLAdlCalendarElement: {
    prototype: HTMLAdlCalendarElement;
    new (): HTMLAdlCalendarElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'adl-calendar': HTMLAdlCalendarElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AdlCalendar extends JSXBase.HTMLAttributes<HTMLAdlCalendarElement> {
    'colorInput'?: string;
    'endyear'?: number;
    'first'?: string;
    'last'?: string;
    'middle'?: string;
    'startyear'?: number;
    'titleCard'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'adl-calendar': AdlCalendar;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


